version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  web_run:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py ensure_superuser --username bfportal --email superuser@bfportal.com --password ${SU_PASSWD} &&  python manage.py ensure_initialization && python manage.py runserver 0.0.0.0:8000 --settings=bfportal.settings.production"
    profiles:
      - donotstart
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    environment:
      - PRODUCTION_KEY=${PRODUCTION_KEY}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_SECRET=${DISCORD_SECRET}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=db # takes precedent over .env file
    depends_on:
      - db
