version: "3"

services:
    db:
      image: postgres
      volumes:
        - postgress_db:/var/lib/postgresql/data
      environment:
        - POSTGRES_NAME=${DB_NAME}
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}

    web_run:
      image: docker.pkg.github.com/battlefield-portal-community/bfportal.gg/bfportal-community:latest
      command: bash -c "python manage.py migrate --noinput && python manage.py ensure_superuser --username bfportal --email superuser@bfportal.com --password '${SU_PASSWD}' &&  python manage.py ensure_initialization && python manage.py runserver 0.0.0.0:8000 --settings=bfportal.settings.production"
      ports:
        - "8000:8000"
      environment:
        - PRODUCTION_KEY=${PRODUCTION_KEY}
        - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
        - DISCORD_SECRET=${DISCORD_SECRET}
        - DB_NAME=${DB_NAME}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - POSTGRES_HOST=db # takes precedent over .env file
        - DEBUG=False
      depends_on:
        - db
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s

volumes:
   postgress_db: